### PR TITLE
Implemented multi-predicate support #103

### PR DESCRIPTION
**Pull request by sam-ulrich1**
This should introduce multi-predicate support. This implementation will fail an entire QueryMatch for a single failed predicate. It is my assumption that this may not be the desired behavior. For example, in the case that you only want a sub-capture to be filtered we may want to modify this to apply predicates within the tree-heirarchy.

Ex:
```
(
  (class_definition 
    name: (identifier) @class.name 
    body: (block 
      (function_definition 
        name: (identifier) @method.name
      ) @class.body 
      (#eq? @method.name "__init__")
    )
  ) 
  (#eq? @class.name "Example")
)
```

In this case would we want to apply the internal method name predicate to just the block element or to the whole querymatch? The current implementation will block the querymatch globally

### CODE REVIEW

**Comment by sam-ulrich1** [comment]
This needs a proper reference to where I got most of the code. Sorry, I thought I had done proper attribution!

Most of the source changes came from https://github.com/klothoplatform/go-tree-sitter but without the changes to the struct so that it could be merged. I'll have to add proper attribution in the source before a merge would be appropriate

**Review by d4vdvd — APPROVED** [review]

**Comment by cdmistman** [comment]
👋 @smacker any chance this can be merged soon? I can try this PR in https://github.com/replit/upm to test if you'd like

**Comment by smacker** [comment]
@sam-ulrich1 could you please remove `.idea` files from the PR?

**Comment by sam-ulrich1** [comment]
Ya, my bad. I'll try to get that done today. If not tomorrow at the latest

**Comment by sam-ulrich1** [comment]
I'll add the proper attribution when I do as well

**Comment by sam-ulrich1** [comment]
@smacker Should be good to go

**Comment by smacker** [comment]
Thank you. Merged.

**Pull request merged**
