### PR TITLE
Switch to a new Python grammar

### PR DESCRIPTION
**Pull request by dennwc**
The #21 mentions briefly that the currently used grammar for Python may not work for Python 3. This PR pins a specific commit from `master` that fixes issues with Python 3 parsing.

Signed-off-by: Denys Smirnov <denis.smirnov.91@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/smacker/go-tree-sitter/23)

### CODE REVIEW

**Comment by smacker** [comment]
Hi Denis!
I checked the diff between v0.15.0 and master and it doesn't look like there are any critical fixes that can't just wait a new release of the grammar.
Thanks.

**Comment by dennwc** [comment]
Even [this one](https://github.com/tree-sitter/tree-sitter-python/compare/v0.15.0..master#diff-95fc33185b7215010b60f43469000a7aR115)? And [this change](https://github.com/tree-sitter/tree-sitter-python/compare/v0.15.0..master#diff-95fc33185b7215010b60f43469000a7aR347)? And named fields for most of the recognized structures? I think those can be called important enough on their own.

Since it doesn't break anything (otherwise we wouldn't use it), I don't see a reason why adding it is a bad idea.

**Comment by smacker** [comment]
> I think those can be called important enough on their own.

Important but not critical.

> Since it doesn't break anything (otherwise we wouldn't use it), I don't see a reason why adding it is a bad idea.

That means updating grammars for each language on each commit which I would prefer to avoid. The better way would be to create an issue in the grammar repository asking if there any reason not to release new patch version.

**Comment by dennwc** [comment]
> Important but not critical.

Depends on the use case. As you may know, those few fixes are critical for ours. May not be critical for other users, but it won't hurt them either. On the contrary: it will allow them to query fields by name for Python, which is useful to understand the parse tree.

> That means updating grammars for each language on each commit which I would prefer to avoid.

We don't want to update on each commit either, but sometimes it's necessary to move forward without waiting for upstream to release patches.

So at the end, it depends on why it's a problem for this specific PR. If you don't have time to review it, lets discuss how we can bring another maintainer in, so he can help you with reviews.

And we want to help with this specific one, because again, updating projects to include important fixes is always good, even if upstream is moving slower in terms of releases. It (ideally) should not delay users and use cases of this cool Go library.

**Comment by smacker** [comment]
I totally understand your point.
There is always a tradeoff in software development between speed and maintainability.
In this case, I choose maintainability as it makes it much more clear what the binding depends on using tags vs sha1s. Plus it allows automatization like `./vendor.sh check-updates` (and automatic updates in the future).

For time-sensitive non-open-source projects which require specific fixes/improvements it is usually a good idea to maintain private/company fork.

About the maintainers as discussed before the idea is to move this binding to tree-sitter organization when the lib becomes a bit more mature though it might don't solve your problem as most probably you will need an agreement between maintainers for such type of changes.

Thank you.

P.S. I opened an issue in the grammar repo.

**Comment by dennwc** [comment]
> I choose maintainability

Sorry, but I fail to see how the tag is different from a commit hash from a maintenance standpoint.

If it's not clear why the tag was chosen, I can put a comment explaining it. Other than that, from technical perspective, it works exactly the same: `git clone -b xxx`. If you are worried about  `./vendor.sh check-updates`, I can make it work in both cases if it isn't already (haven't checked).

> For time-sensitive non-open-source projects

FYI, it is [open source](https://github.com/src-d/imports). And it helped to identify a few critical issues in this library that we backported, as you may know. Maybe it makes sense to say "thanks" and help us as well with this simple change?

> I opened an issue in the grammar repo.

Could you link to it? Thanks.

**Comment by smacker** [comment]
> Sorry, but I fail to see how the tag is different from a commit hash from a maintenance standpoint.

1. Tag follows semver so updating in most cases (patch version) can be automatic/semi-automatic.
2. Using sha1s would require either updating on each commit or invent some strategy why we actually update it.
3. Check #24 (WIP) but gives you an idea. Pushing tags for each grammar for each sha1 doesn't sound good for me.

**Comment by smacker** [comment]
> Could you link to it? Thanks.

https://github.com/tree-sitter/tree-sitter-python/issues/59

**Comment by dennwc** [comment]
I like the general direction of https://github.com/smacker/go-tree-sitter/pull/24, this way it will be possible to update to tags in `master`, while still keeping stable releases in tags.

**Comment by smacker** [comment]
Hi @dennwc 

All the changes you need were pulled by this commit: https://github.com/smacker/go-tree-sitter/commit/9e37a69d4b1def11318f530584fc8616eeefe0d3

**Pull request closed without merging**
