### PR TITLE
cstdint is required

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by smacker** [comment]
Could you please clarify why `cstdint` is required? The test for yaml parser passes correctly for me.

**Comment by mattn** [comment]
`int8_t` is defined in cstdint. (stdint.h for C)

**Comment by smacker** [comment]
Hi @mattn . As you correctly pointed out, the type definition is already included in `stdint.h` which is imported in the parser that results in a correct build.

Though I do understand your concern. Please open an issue or PR to the [yaml-grammar repository](https://github.com/ikatyang/tree-sitter-yaml) instead. This project provides binding to Golang only. I will be happy to [update the version](https://github.com/smacker/go-tree-sitter/blob/master/vendor.sh#L27) of the grammar after the changes merged and released.

Thank you.

**Comment by mattn** [comment]
Sure. https://github.com/ikatyang/tree-sitter-yaml/pull/31

**Pull request closed without merging**
