### PR TITLE
Add SQL bindings support

### PR DESCRIPTION
**Pull request by vladlyt**
Adding SQL bindings support from looks like most popular library for the SQL https://github.com/DerekStride/tree-sitter-sql

Please consider adding it

### CODE REVIEW

**Comment by vladlyt** [comment]
Hey @smacker, can please check this PR?

**Comment by smacker** [comment]
@vladlyt thank you! Looks good to me! Could you please rebase on master?

**Comment by vladlyt** [comment]
@smacker updated PR

**Comment by smacker** [comment]
thank you @vladlyt !

**Pull request merged**
