### PR TITLE
Improve updater and Go -> 1.20

### PR DESCRIPTION
**Pull request by asalvi0**
Cleaned up the `UpdateAll` method to reuse `Update`, should be easier to maintain.

**Notes:**
_The additional indirect dependencies in `go.sum` come from `github.com/stretchr/testify` after running `go mod tidy`_

### CODE REVIEW

**Comment by smacker** [comment]
hi @asalvi0 ! Thank you! But let's support at least 3 latest versions of go. No everybody migrates immediately :)

**Comment by asalvi0** [comment]
> hi @asalvi0 ! Thank you! But let's support at least 3 latest versions of go. No everybody migrates immediately :)

Downgraded to `1.20`; all tests are passing locally.

**Comment by smacker** [comment]
Could you please update this file https://github.com/smacker/go-tree-sitter/blob/master/.github/workflows/test.yml by removing go1.19 and adding go1.23? Looks like I can't push into your branch. Otherwise the CI will fail.

**Comment by asalvi0** [comment]
> Could you please update this file https://github.com/smacker/go-tree-sitter/blob/master/.github/workflows/test.yml by removing go1.19 and adding go1.23? Looks like I can't push into your branch. Otherwise the CI will fail.

@smacker done.

**Comment by smacker** [comment]
thank you!

**Pull request merged**
